<a href="https://colab.research.google.com/github/lululu-mia/Data-Science/blob/main/Homework/HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Data Science HW2**


### Numpy

In [1]:
import numpy as np

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [2]:
# Define two numpy arrays
A = np.array([1, 2, 3, 4, 5])
B = np.array([4, 5, 6, 7, 8])

# Stack arrays vertically (one on top of the other)
v_stack = np.vstack((A, B))
print("Vertical Stack:\n", v_stack)

# Stack arrays horizontally (side by side)
h_stack = np.hstack((A, B))
print("\nHorizontal Stack:\n", h_stack)

Vertical Stack:
 [[1 2 3 4 5]
 [4 5 6 7 8]]

Horizontal Stack:
 [1 2 3 4 5 4 5 6 7 8]


2. Find common elements between A and B. [Hint : Intersection of two sets]

In [3]:
common_elements = np.intersect1d(A, B)
print("Common elements between A and B:", common_elements)

Common elements between A and B: [4 5]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [5]:
filtered_values = A[np.where((A >= 5) & (A <= 10))]
print(filtered_values)

[5]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [6]:
# Load the Iris dataset from UCI repository
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Apply the filtering conditions
filtered_rows = iris_2d[(iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0)]
print("Filtered iris rows:\n", filtered_rows)

Filtered iris rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Pandas

In [7]:
import pandas as pd

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_20th = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_20th)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [11]:
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

print(df[['Min.Price', 'Max.Price']].head(10))

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091
5  14.200000  17.300000
6  19.900000  21.459091
7  22.600000  24.900000
8  26.300000  26.300000
9  33.000000  36.300000


3. How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [10]:
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rows_sum_gt_100 = df_random[df_random.sum(axis=1) > 100]

print(rows_sum_gt_100)

    0   1   2   3
2  17  38  36  33
3  30  27  18  33
4  21  19  36  32
5  32  22  33  38
